"""
BIS AI V2 — Multi-Agent Supervisor & Intent Router
Orchestrates:
  1. Intent Classification & Agent Selection
  2. Four Specialist Agents:
     - Standards Agent (Standards discovery & technical scope)
     - Compliance Agent (QCOs, statutory penalties & certification schemes)
     - Manufacturer Agent (Compliance roadmap, Form-V checklist, lab matching)
     - Consumer Agent (Verification of CM/L & HUID, complaint guidance)
  3. Safe Progress Telemetry (Non-exposed internal chain-of-thought)
  4. Strict Statutory Disclaimers
"""

import logging
import time
import uuid

from rag import generate_grounded_answer
from schemas.api_models import ChatResponse

logger = logging.getLogger("bis.agents")


class AgentRouter:
    """Classifies user intent and routes to specialized BIS AI domain agents."""

    @staticmethod
    def classify_intent(query: str, requested_role: str | None = None) -> str:
        """Classify query into standards | compliance | manufacturer | consumer."""
        if requested_role and requested_role in ("standards", "compliance", "manufacturer", "consumer"):
            return requested_role

        q = query.lower()

        # Consumer cues
        if any(w in q for w in ["consumer", "fake", "duplicate", "genuine", "verify", "huid", "complaint", "cheat", "scam", "cm/l", "hallmark", "bis care"]):
            return "consumer"

        # Manufacturer & Roadmap cues
        if any(w in q for w in ["manufacturer", "factory", "msme", "form-v", "form v", "roadmap", "apply", "license", "fee", "cost", "turnaround", "audit", "laboratory", "booking"]):
            return "manufacturer"

        # Compliance & Regulatory cues
        if any(w in q for w in ["qco", "quality control order", "mandatory", "penalty", "section 29", "scheme-i", "scheme-ii", "crs", "fmcs", "statutory", "act"]):
            return "compliance"

        # Default to Standards agent
        return "standards"

    @classmethod
    async def route_and_execute(
        cls,
        query: str,
        language: str = "en",
        role: str | None = "all"
    ) -> ChatResponse:
        """Execute routed multi-agent pipeline with safe telemetry."""
        t0 = time.time()
        trace_id = f"trace-bis-{uuid.uuid4().hex[:10]}"

        # 1. Intent Classification
        agent_type = cls.classify_intent(query, requested_role=role)
        logger.info(f"[{trace_id}] Query routed to specialist: {agent_type} (Query: '{query[:60]}...')")

        # 2. Specialist Execution via Grounded RAG
        answer, citations, confidence, next_steps = await generate_grounded_answer(
            query=query,
            language=language,
            role=agent_type
        )

        # 3. Add Domain Specific Advisories
        if agent_type == "manufacturer":
            answer += (
                "\n\n---\n**Statutory Advisory for Manufacturers & MSMEs:**\n"
                "This roadmap is generated by BIS AI for pre-certification preparation. "
                "Official application submission, statutory fee deposit, and digital grant of license "
                "must be completed via the official portal: **[Manak Online](https://www.manakonline.in)**."
            )
        elif agent_type == "consumer":
            answer += (
                "\n\n---\n**Consumer Protection Notice:**\n"
                "Verify live licence details via the free **BIS CARE App** by entering the CM/L number or 6-character HUID. "
                "National Consumer Helpline: **1800-11-4070**."
            )

        elapsed_ms = int((time.time() - t0) * 1000)

        return ChatResponse(
            answer=answer,
            agent=agent_type,
            confidence=confidence,
            citations=citations,
            next_steps=next_steps,
            trace_id=trace_id,
            latency_ms=elapsed_ms
        )


# Singleton
agent_router = AgentRouter()
